name: Build LSPosed Module

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v4

    - name: Build with Gradle
      run: gradle assembleDebug

    - name: Upload build outputs
      uses: actions/upload-artifact@v4
      with:
        name: AOD-Fix-APK
        path: app/build/outputs/apk/debug/app-debug.apk
